# Generated by Django 4.2.2 on 2023-07-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
