# Generated by Django 4.2.2 on 2023-06-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Landmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("location_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("location_lon", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="landmark_thumbnails/"
                    ),
                ),
            ],
        ),
    ]
