# Generated by Django 4.2.2 on 2023-06-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landmark", "0003_alter_landmark_location_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landmark",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
